swagger: '2.0'
info:
  title: OpenAPI 2.0 array items allOf example
  version: '1'
definitions:
  ArrayWithAllOfObjects:
    type: array
    items:
      allOf:
        - type: object
          properties:
            id:
              type: integer
        - type: object
          properties:
            name:
              type: string
  ArrayWithAllOfPrimitives:
    type: array
    items:
      allOf:
        - type: number
        - type: string
  ArrayWithAllOfRefs:
    type: array
    items:
      allOf:
        - $ref: '#/definitions/BaseModel'
        - type: object
          properties:
            extra:
              type: string
  BaseModel:
    type: object
    properties:
      id:
        type: integer
      createdAt:
        type: string
        format: date-time
