swagger: 2.0
info:
  title: OpenAPI 2.0 type format example
  version: 1
paths:
  /foo:
    post:
      produces:
        - application/json
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/Foo'
definitions:
  Foo:
    type: object
    properties:
      bar:
        type: integer
      foo:
        default: 0
        format: int64
        type: integer
      id:
        type: string
        format: typeid
        example: 'user_123'
    required:
      - id
      - foo
  Bar:
    type: object
    required:
      - foo
    properties:
      foo:
        type: integer
    additionalProperties:
      type: integer
