openapi: 3.1.0
info:
  title: OpenAPI 3.1.0 array items allOf example
  version: '1'
components:
  schemas:
    # Test case 1: Array with allOf of object schemas
    ArrayWithAllOfObjects:
      type: array
      items:
        allOf:
          - type: object
            properties:
              id:
                type: integer
          - type: object
            properties:
              name:
                type: string
    # Test case 2: Array with allOf of primitives
    ArrayWithAllOfPrimitives:
      type: array
      items:
        allOf:
          - type: number
          - type: string
    # Test case 3: Array with allOf including refs
    ArrayWithAllOfRefs:
      type: array
      items:
        allOf:
          - $ref: '#/components/schemas/BaseModel'
          - type: object
            properties:
              extra:
                type: string
    BaseModel:
      type: object
      properties:
        id:
          type: integer
        createdAt:
          type: string
          format: date-time
