openapi: 3.1.0
info:
  title: OpenAPI 3.1.0 content types example
  version: '1'
paths:
  /foo:
    get:
      responses:
        '200':
          description: OK
          content:
            text/plain:
              schema:
                type: string
            application/json:
              schema:
                type: string
            text/json:
              schema:
                type: string
