openapi: 3.1.0
info:
  title: OpenAPI 3.1.0 enum inline example
  version: '1'
paths:
  /foo:
    get:
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  foo:
                    type: string
                    enum:
                      - foo
                      - bar
    post:
      responses:
        '200':
          description: 'OK'
          content:
            application/json:
              schema:
                type: object
                properties:
                  foo:
                    type: string
                    enum:
                      - baz
    put:
      responses:
        '200':
          description: 'OK'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Baz'
components:
  schemas:
    Foo:
      properties:
        type:
          enum:
            - foo
            - bar
          type: string
      type: object
    Bar:
      properties:
        type:
          $ref: '#/components/schemas/Baz'
      type: object
    Baz:
      enum:
        - qux
        - quux
      type: string
