openapi: '3.1.0'
info:
  title: Integer Formats Test
  version: '1.0.0'
components:
  schemas:
    IntegerFormats:
      type: object
      properties:
        numberNoFormat:
          type: number
        numberInt8:
          type: number
          format: int8
        numberInt16:
          type: number
          format: int16
        numberInt32:
          type: number
          format: int32
        numberInt64:
          type: number
          format: int64
        numberUint8:
          type: number
          format: uint8
        numberUint16:
          type: number
          format: uint16
        numberUint32:
          type: number
          format: uint32
        numberUint64:
          type: number
          format: uint64
        integerNoFormat:
          type: integer
        integerInt8:
          type: integer
          format: int8
        integerInt16:
          type: integer
          format: int16
        integerInt32:
          type: integer
          format: int32
        integerInt64:
          type: integer
          format: int64
        integerUint8:
          type: integer
          format: uint8
        integerUint16:
          type: integer
          format: uint16
        integerUint32:
          type: integer
          format: uint32
        integerUint64:
          type: integer
          format: uint64
        stringInt64:
          type: string
          format: int64
        stringUint64:
          type: string
          format: uint64
