openapi: 3.1.0
info:
  title: OpenAPI 3.1.0 validators example
  version: '1'
paths:
  /foo:
    patch:
      parameters:
        - $ref: '#/components/parameters/Foo'
        - in: query
          name: bar
          required: false
          schema:
            $ref: '#/components/schemas/Bar'
        - in: query
          name: baz
          required: false
          schema:
            properties:
              baz:
                type: string
            type: object
        - in: query
          name: qux
          required: false
          schema:
            format: date
            type: string
        - in: query
          name: quux
          required: false
          schema:
            format: date-time
            type: string
      requestBody:
        content:
          'application/json':
            schema:
              properties:
                foo:
                  type: string
              type: object
        required: true
      responses:
        '200':
          description: OK
    post:
      requestBody:
        $ref: '#/components/requestBodies/Foo'
      responses:
        '200':
          description: OK
components:
  parameters:
    Foo:
      description: 'This is Foo parameter.'
      name: foo
      in: query
      required: false
      schema:
        type: string
  requestBodies:
    Foo:
      required: true
      content:
        'application/json':
          schema:
            type: object
            properties:
              foo:
                $ref: '#/components/schemas/Bar'
  schemas:
    Foo:
      default: null
      description: 'This is Foo schema.'
      properties:
        foo:
          description: 'This is foo property.'
          pattern: ^\d{3}-\d{2}-\d{4}$
          type: string
        bar:
          $ref: '#/components/schemas/Bar'
        baz:
          description: 'This is baz property.'
          items:
            $ref: '#/components/schemas/Foo'
          type: array
        qux:
          description: 'This is qux property.'
          default: 0
          exclusiveMinimum: 0
          type: integer
      type:
        - object
        - 'null'
    Bar:
      description: 'This is Bar schema.'
      properties:
        foo:
          $ref: '#/components/schemas/Foo'
      type: object
    Baz:
      default: baz
      pattern: foo\nbar
      readOnly: true
      type: string
    Qux:
      additionalProperties:
        properties:
          qux:
            type: string
        type: object
      type: object
