openapi: 3.1.1
info:
  title: OpenAPI 3.1.1 validators circular ref 2 example
  version: 1
components:
  schemas:
    Foo:
      additionalProperties: false
      properties:
        foo:
          $ref: '#/components/schemas/Bar'
      required:
        - foo
      type: object
    Bar:
      additionalProperties: false
      properties:
        bar:
          items:
            $ref: '#/components/schemas/Bar'
          type:
            - array
            - 'null'
      required:
        - bar
      type: object
