openapi: 3.0.4
info:
  title: Invalid OpenAPI 3.0.4 operationId unique example
  version: 1
paths:
  /foo:
    get:
      operationId: foo
      responses:
        '200':
          content:
            '*/*':
              schema:
                type: string
          description: OK
    post:
      operationId: foo
      responses:
        '200':
          content:
            '*/*':
              schema:
                type: string
          description: OK
