openapi: 3.1.1
info:
  title: Multi A 3.1.x
  version: 1.0.0
paths:
  /a:
    get:
      summary: Get A
      responses:
        '200':
          description: ok
          content:
            application/json:
              schema:
                type: object
                properties:
                  a:
                    type: string
