name: Coverage

on:
  push:
    branches:
      - main
    paths-ignore:
      - docs/**
  pull_request:
    paths-ignore:
      - docs/**

concurrency:
  group: ${{ github.workflow }}=${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  upload:
    name: Upload
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        node-version: ['24.10.0']
    steps:
      - uses: actions/checkout@v5.0.0

      - uses: pnpm/action-setup@v4.1.0

      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Build packages
        run: pnpm build --filter="@hey-api/**"

      - name: Run test coverage
        run: pnpm test:coverage

      - name: Upload code coverage to codecov.io
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          directory: ./packages/openapi-ts/coverage
          flags: unittests
          fail_ci_if_error: true
